title: Thinkofname's blog
email: your-email@domain.com
description: >
  A blog about the development of UniverCity and
  various rust projects.

# Build settings
markdown: kramdown
sass:
    style: compressed
compress_html:
  clippings: all
  comments: all
plugins:
  - jekyll-feed
  - jekyll-redirect-from